export const siteDefaults = {
  heroEyebrow: 'Desenvolvimento web para empresas',
  heroTitleFirst: 'Sites de alto nível.',
  heroTitleSecond: 'Construídos para escalar.',
  heroLead: 'Sites institucionais, e-commerce, landing pages e plataformas sob medida com IA. Rápidos, acessíveis e prontos para crescer com a sua operação.',
  solutionsTitleFirst: 'Do primeiro site',
  solutionsTitleSecond: 'à plataforma com IA.',
  solutionsIntro: 'Cada projeto começa pelo objetivo do negócio. A tecnologia vem depois, na medida certa.',
  projectsTitle: 'O que já está no ar.',
  projectsIntro: 'Sites, landing pages e páginas de contato para empresas de vários segmentos, independentes e em parceria com a 3ADS. Abra um projeto para ver a ideia e como ficou.',
  processTitleFirst: 'Do briefing ao site no ar.',
  processTitleSecond: 'Com prazo em cada etapa.',
  processIntro: 'Você sabe o que acontece, quando acontece e o que precisa fazer. Nenhuma etapa avança sem a sua aprovação.',
  aboutTitleFirst: 'Prazer,',
  aboutTitleSecond: 'Thiago Barreto.',
  aboutIntro: 'Sou UX/UI Developer e crio sites e landing pages baseados em estratégia.',
  aboutBody: 'Trabalho com WordPress, ferramentas low-code e código sob medida, transformando layouts em páginas rápidas, funcionais e pensadas para conversão.',
  pillarOneTitle: 'Experiência clara.',
  pillarOneText: 'Estruturas consistentes de UX e padrões de uso que o visitante já conhece. Ninguém precisa pensar para achar o que procura.',
  pillarTwoTitle: 'Visual que se destaca.',
  pillarTwoText: 'Design e comunicação adaptados aos objetivos de cada negócio, em vez de um modelo pronto.',
  pillarThreeTitle: 'Estrutura que leva à ação.',
  pillarThreeText: 'Cada seção conduz o visitante um passo mais perto do contato, da compra ou do cadastro.',
  blogTitleFirst: 'Ideias para levar',
  blogTitleSecond: 'o seu site mais longe.',
  blogIntro: 'Conteúdo sobre sites, experiência e tecnologia, direto do meu blog.',
  contactTitleFirst: 'Vamos conversar sobre',
  contactTitleSecond: 'o seu projeto?',
  contactIntro: 'Uma conversa rápida para entender seu objetivo e ver se faz sentido trabalharmos juntos. Preencha abaixo e a mensagem chega pronta no meu WhatsApp.',
  footerTitleFirst: 'Vamos construir',
  footerTitleSecond: 'o que vem depois.',
  footerBio: 'UX/UI Developer. Sites e landing pages baseados em estratégia.',
} as const

export type SiteContentKey = keyof typeof siteDefaults
